'use client';
import {useState} from 'react';
import {ArrowLeft,ArrowLeftRight,ArrowUpRight,Info} from 'lucide-react';
import {Select,SelectTrigger,SelectContent,SelectValue,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {compareProfiles,companyPeriod,directoryReadout} from '@/lib/company/radar';
import {RadarPlot,RadarScaleGuide,PROFILE_COLORS} from './radar-profile';
import {safeURL,type Company,type MetricId} from '@/lib/company/model';
export function CompanyComparison({companies,pair,onPair,onBack,onOpen}:{companies:Company[];pair:[Company,Company];onPair:(ids:string[])=>void;onBack:()=>void;onOpen:(c:Company)=>void}){
 const [selected,setSelected]=useState<MetricId>('growth');
 const [a,b]=pair,comparison=compareProfiles(a,b),focus=comparison.rows.find(r=>r.left.id===selected)!;
 return <main className="comparison-page"><button className="back-to-directory" onClick={onBack}><ArrowLeft size={15}/>Companies</button><div className="comparison-heading"><div><span className="eyebrow">SIDE BY SIDE</span><h1>Compare the signals<span>.</span></h1></div><RadarScaleGuide/></div>
 <div className="comparison-pickers">{pair.map((c,i)=><div className="comparison-picker" key={i}><span className="comparison-color" style={{background:PROFILE_COLORS[i]}}/><Select value={c.id} onValueChange={id=>onPair(i===0?[id,b.id]:[a.id,id])}><SelectTrigger aria-label={i===0?'First company':'Second company'}><SelectValue/></SelectTrigger><SelectContent>{companies.map(option=><SelectItem key={option.id} value={option.id} disabled={option.id===pair[1-i].id}>{option.name}</SelectItem>)}</SelectContent></Select><span className="picker-period">{companyPeriod(c)}</span></div>)}<button className="swap-companies" aria-label="Swap companies" onClick={()=>onPair([b.id,a.id])}><ArrowLeftRight size={17}/></button></div>
 <div className="comparison-visual"><div className="comparison-radar"><RadarPlot company={a} other={b} axes={comparison.shared} selected={selected} onSelect={setSelected}/><p><Info size={14}/>Only shared, compatible dimensions are plotted. More area is not an overall safety score.</p></div><aside className="comparison-focus"><span className="eyebrow">SELECTED DIMENSION</span><h2>{focus.left.label}</h2><div className="comparison-focus-values">{pair.map((c,i)=><div key={c.id}><span style={{color:PROFILE_COLORS[i]}}>{c.name}</span><strong>{(i===0?focus.left:focus.right).value}</strong></div>)}</div><p>{focus.comparable?focus.left.detail:focus.reason+'. This dimension is excluded from the comparison radar.'}</p><div className="comparison-readouts">{pair.map((c,i)=>{const read=directoryReadout(c);return <div key={c.id}><span>{c.name}</span><strong className={read.tone}>{read.label}</strong><small>{read.positive} positive · {read.review} review · {read.unknown} unknown</small><button onClick={()=>onOpen(c)}>Open report <ArrowUpRight size={13}/></button></div>})}</div></aside></div>
 <div className="comparison-table-heading"><h2>The figures behind the shape</h2><span>{comparison.shared.length} / 6 dimensions comparable</span></div><div className="comparison-table"><Table><TableHeader><TableRow><TableHead>Dimension</TableHead><TableHead>{a.name}</TableHead><TableHead>{b.name}</TableHead><TableHead>In the radar</TableHead></TableRow></TableHeader><TableBody>{comparison.rows.map(row=><TableRow key={row.left.id} data-selected={selected===row.left.id}><TableCell><button onClick={()=>setSelected(row.left.id)}>{row.left.label}</button></TableCell>{[row.left,row.right].map((r,i)=><TableCell key={i}><strong>{r.value}</strong><small>{r.period||'No reporting period'}{r.date?' · '+r.date:''}</small>{safeURL(pair[i].metrics[r.id]?.url??'')&&<a href={safeURL(pair[i].metrics[r.id]!.url)} target="_blank" rel="noopener noreferrer">Source <ArrowUpRight size={11}/></a>}</TableCell>)}<TableCell><span className={row.comparable?'comparable-tag':'excluded-tag'}>{row.comparable?'Included':row.reason}</span></TableCell></TableRow>)}</TableBody></Table></div>
 </main>;
}
