'use client';
import {useState} from 'react';
import {Search,Plus,ArrowUpRight,ArrowRight,GitCompareArrows,X,CheckCircle2} from 'lucide-react';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {companyMeta} from '@/lib/company/data';
import {companyPeriod,directoryReadout} from '@/lib/company/radar';
import {SIGNAL_COLORS} from '@/lib/company/visuals';
import {specs,type Company} from '@/lib/company/model';
export function CompanyDirectory({companies,selected,onSelected,onOpen,onCompare,onCreate}:{companies:Company[];selected:string[];onSelected:(ids:string[])=>void;onOpen:(company:Company)=>void;onCompare:()=>void;onCreate:(name:string)=>void}){
 const [query,setQuery]=useState(''),[adding,setAdding]=useState(false),[name,setName]=useState('');
 const filtered=companies.filter(c=>[c.name,c.entity,...(companyMeta[c.id]?.aliases??[])].join(' ').toLowerCase().includes(query.trim().toLowerCase()));
 function toggle(id:string){onSelected(selected.includes(id)?selected.filter(x=>x!==id):selected.length<2?[...selected,id]:selected);}
 return <main className="directory-page"><div className="directory-heading"><div><span className="eyebrow">YOUR NEXT MOVE STARTS HERE</span><h1>Companies<span>.</span></h1><p>Open a company, or select two to compare their signals.</p></div><button className="button primary" onClick={()=>setAdding(true)}><Plus size={17}/>Add company</button></div>
 <div className="directory-tools"><div className="directory-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search companies or entities" aria-label="Search companies"/>{query&&<button aria-label="Clear search" onClick={()=>setQuery('')}><X size={15}/></button>}</div><span>{filtered.length} compan{filtered.length===1?'y':'ies'}</span><button className="button compare-action" disabled={selected.length!==2} onClick={onCompare}><GitCompareArrows size={16}/>Compare {selected.length}/2</button></div>
 <div className="directory-table"><Table><TableHeader><TableRow><TableHead><span className="sr-only">Select for comparison</span></TableHead><TableHead>Company</TableHead><TableHead>At a glance</TableHead><TableHead>Revenue growth</TableHead><TableHead>Operating margin</TableHead><TableHead>Data coverage</TableHead><TableHead><span className="sr-only">Open company</span></TableHead></TableRow></TableHeader><TableBody>{filtered.map(c=>{
 const read=directoryReadout(c),meta=companyMeta[c.id],growth=read.results[3],margin=read.results[4],edited=Object.values(c.metrics).some(m=>m?.origin==='user');
 return <TableRow key={c.id} data-selected={selected.includes(c.id)}><TableCell><Checkbox aria-label={'Compare '+c.name} checked={selected.includes(c.id)} disabled={selected.length===2&&!selected.includes(c.id)} onCheckedChange={()=>toggle(c.id)}/></TableCell><TableCell><button className="directory-company" onClick={()=>onOpen(c)}><span className={'directory-monogram '+c.id}>{c.name.slice(0,1)}</span><span><strong>{c.name}<ArrowUpRight size={14}/></strong><small>{meta?.ticker??'Your research'} · {meta?.sector??c.entity}</small></span></button></TableCell><TableCell><span className={'directory-readout '+read.tone}>{read.label}</span><div className="directory-signal-bar">{read.results.map((r,i)=><span key={specs[i].id} style={{background:SIGNAL_COLORS[r.tone]}} title={specs[i].title+': '+r.label}/>)}</div><small className="directory-counts">{read.positive} positive · {read.review} review · {read.unknown} unknown</small></TableCell><TableCell><span className={'directory-value '+growth.tone}>{growth.stale?'—':growth.value}<small>{growth.stale?'':growth.unit}</small></span></TableCell><TableCell><span className={'directory-value '+margin.tone}>{margin.stale?'—':margin.value}<small>{margin.stale?'':margin.unit}</small></span></TableCell><TableCell><strong className="directory-coverage">{read.results.filter(r=>r.complete&&!r.stale).length}<small> / 6</small></strong><span className="directory-period">{companyPeriod(c)}</span><small className="directory-origin">{edited?'Your figures':meta?'Curated snapshot':'Manual research'}</small></TableCell><TableCell><button className="directory-open" aria-label={'Open '+c.name} onClick={()=>onOpen(c)}><ArrowRight size={20}/></button></TableCell></TableRow>
 })}</TableBody></Table></div>
 {!filtered.length&&<div className="directory-empty"><Search size={25}/><h2>No matching companies</h2><p>Create a manual check for the company you have in mind.</p><button className="button secondary" onClick={()=>{setName(query);setAdding(true)}}><Plus size={16}/>Add company</button></div>}
 <div className="directory-foot"><span><CheckCircle2 size={15}/>Dated sources and visible data gaps</span><p>Curated snapshots are not live feeds. Signals are screening checks, not a guarantee of job security.</p></div>
 {selected.length>0&&<div className="selection-tray"><span>{selected.length===1?'Choose one more company':'Ready to compare'}</span><div>{selected.map(id=><button key={id} onClick={()=>toggle(id)}>{companies.find(c=>c.id===id)?.name}<X size={13}/></button>)}</div><button className="button primary" disabled={selected.length!==2} onClick={onCompare}>Compare profiles <ArrowRight size={16}/></button><button className="clear-selection" onClick={()=>onSelected([])}>Clear</button></div>}
 <Dialog open={adding} onOpenChange={setAdding}><DialogContent className="metric-dialog"><DialogHeader><DialogTitle>Add a company</DialogTitle><DialogDescription>Start a check with your own figures, or open an existing report.</DialogDescription></DialogHeader><form className="editor-form" onSubmit={e=>{e.preventDefault();if(!name.trim())return;onCreate(name.trim());setAdding(false);setName('')}}><label>Company name or UEN<input autoFocus required maxLength={120} value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. your prospective employer"/></label><button className="button primary" type="submit">Open company check <ArrowRight size={16}/></button></form></DialogContent></Dialog>
 </main>;
}
