'use client';
import {useEffect,useState} from 'react';
import {ArrowUpRight,ArrowRight,Search,Bookmark,Building2,ShieldCheck,Activity,FileText,Plus,Check,ExternalLink,Clock,Trash2,Eye,BriefcaseBusiness,Info,ChevronRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Toaster,toast} from 'sonner';
type Evidence={id:string;category:string;signal:string;note:string;url:string;date:string};
type Company={id:string;name:string;entity:string;evidence:Evidence[];reviewed:string;next:string;checks:string[]};
const categories=['Financial position','Business momentum','People & operations','Legal & governance'];
const source='https://www.grab.com/sg/press/others/grab-reports-record-second-quarter-2026-results-raises-full-year-guidance-and-announces-750-million-share-repurchase-program/';
const sample:Company={id:'grab',name:'Grab',entity:'Grab Holdings Limited · NASDAQ: GRAB · Group-level report',reviewed:'2026-09-13',next:'',checks:[],evidence:[{id:'g1',category:categories[0],signal:'positive',note:'Q2 2026 profit of US$235 million; trailing 12-month adjusted free cash flow of US$450 million. Adjusted cash flow is a non-IFRS measure.',url:source,date:'2026-08-04'},{id:'g2',category:categories[1],signal:'positive',note:'Q2 2026 revenue of US$997 million, up 22% year-on-year.',url:source,date:'2026-08-04'}]};
const questions=['Confirm the legal entity on your offer or contract.','Ask whether this role is funded for the next 12 months.','Ask why the position is open and how the team has changed.','Ask about cash runway, profitability and financing needs.'];
function status(c:Company){return c.evidence.some(e=>e.signal==='concern')?'Concerns to investigate':c.evidence.length?'Evidence is mixed or incomplete':'Not enough evidence';}
function safeURL(s:string){try{const u=new URL(s);return ['https:','http:'].includes(u.protocol)?u.href:undefined}catch{return undefined}}
const key='shouldijoin.workspace.v1';
export default function Home(){
const [tab,setTab]=useState('check'),[mode,setMode]=useState('joining'),[query,setQuery]=useState(''),[company,setCompany]=useState<Company>(sample),[saved,setSaved]=useState<Company[]>([]),[ready,setReady]=useState(false),[dialog,setDialog]=useState(false),[category,setCategory]=useState(categories[0]),[signal,setSignal]=useState('unknown'),[note,setNote]=useState(''),[url,setUrl]=useState(''),[date,setDate]=useState(''),[storageOK,setStorageOK]=useState(true);
useEffect(()=>{try{const raw=localStorage.getItem(key);if(raw){const parsed=JSON.parse(raw);if(Array.isArray(parsed))setSaved(parsed.filter(c=>c&&typeof c.id==='string'&&typeof c.name==='string'&&Array.isArray(c.evidence)&&Array.isArray(c.checks)));}}catch{setStorageOK(false)}setReady(true)},[]);
useEffect(()=>{if(!ready)return;try{localStorage.setItem(key,JSON.stringify(saved))}catch{setStorageOK(false)}},[saved,ready]);
function openCompany(name:string){const clean=name.trim().slice(0,120);if(!clean)return;const existing=saved.find(c=>c.name.toLowerCase()===clean.toLowerCase());setCompany(existing||(/^grab( holdings( limited)?)?$/i.test(clean)?sample:{id:crypto.randomUUID(),name:clean,entity:'Entity not verified · Confirm registered name and UEN',evidence:[],reviewed:'',next:'',checks:[]}));setQuery('');setTab('check');}
function update(c:Company){setCompany(c);setSaved(prev=>prev.map(x=>x.id===c.id?c:x));}
function save(){setSaved(prev=>[company,...prev.filter(c=>c.id!==company.id)]);toast.success('Added to your watchlist on this device');}
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'start_company_check',description:'Open a company research workspace. Does not fetch live financial data or save a report.',inputSchema:{type:'object',properties:{companyName:{type:'string',minLength:1,maxLength:120}},required:['companyName'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input:any){if(typeof input?.companyName!=='string'||!input.companyName.trim()||input.companyName.length>120)throw new Error('A company name of 1–120 characters is required');openCompany(input.companyName);return {opened:input.companyName.trim(),coverage:'Manual research; Grab has a sourced snapshot'};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort()},[saved]);
const concerns=company.evidence.filter(e=>e.signal==='concern').length,coverage=categories.filter(c=>company.evidence.some(e=>e.category===c)).length,isSaved=saved.some(c=>c.id===company.id);
function addEvidence(e:React.FormEvent){e.preventDefault();if(!note.trim())return;if(url&&!safeURL(url)){toast.error('Use a valid https:// or http:// source URL');return;}update({...company,evidence:[...company.evidence,{id:crypto.randomUUID(),category,signal,note:note.trim(),url,date}],reviewed:new Date().toISOString().slice(0,10)});setDialog(false);setNote('');setUrl('');setDate('');toast.success('Evidence added. '+(isSaved?'Watchlist updated.':'Save this check to keep it.'));}
return <><Toaster position="bottom-right"/><header className="topbar"><a className="brand" href="/" aria-label="Should I Join home"><span className="brand-icon"><Activity size={24}/></span>should i join<span className="brand-period">?</span></a><div className="topnote">A little due diligence. A better next move.</div><span className="beta">EARLY ACCESS</span></header>
<Tabs value={tab} onValueChange={setTab} className="app"><div className="navwrap"><TabsList className="navtabs" variant="line"><TabsTrigger value="check"><Search/>Company check</TabsTrigger><TabsTrigger value="watchlist"><Bookmark/>My watchlist <span className="count">{saved.length}</span></TabsTrigger><TabsTrigger value="method"><ShieldCheck/>Our approach</TabsTrigger></TabsList><span className="local-note"><ShieldCheck size={14}/> Your research stays on this device</span></div>
<TabsContent value="check"><main><div className="page-heading"><div><div className="eyebrow">KNOW MORE BEFORE YOU COMMIT</div><h1>Good opportunity.<br className="mobile-break"/> Healthy company?</h1><p>Look beyond the offer. Understand the business behind it.</p></div><span className="location"><Building2 size={16}/> Singapore focus</span></div>
<div className="search-card"><form onSubmit={e=>{e.preventDefault();openCompany(query)}} className="search-form"><Search size={21}/><label className="sr-only" htmlFor="company-search">Company name or UEN</label><input id="company-search" value={query} onChange={e=>setQuery(e.target.value)} maxLength={120} required placeholder="Enter a company name or UEN"/><button className="primary" type="submit">Check company <ArrowRight size={18}/></button></form><div className="search-under"><span>Try a sourced report: <button className="text-button" onClick={()=>openCompany('Grab')}>Grab <ArrowUpRight size={14}/></button></span><span>Other companies open a guided research check.</span></div></div>
<div className="workspace-grid"><section className="report"><div className="report-heading"><div className={'company-logo '+(company.id==='grab'?'grab':'')} >{company.id==='grab'?'G':company.name.slice(0,2).toUpperCase()}</div><div className="company-title"><h2>{company.name}</h2><p>{company.entity}</p></div><button className={'secondary save '+(isSaved?'saved':'')} onClick={save}><Bookmark size={17} fill={isSaved?'currentColor':'none'}/>{isSaved?'Saved':'Watch company'}</button></div>
<div className="report-meta"><span><FileText size={14}/>{company.id==='grab'?'Sourced snapshot · not live':'Your research workspace'}</span><span><Clock size={14}/>{company.reviewed?'Reviewed '+company.reviewed:'Not reviewed yet'}</span></div>
<div className={'assessment '+(concerns?'has-concerns':'')}><div className="assessment-top"><span className="eyebrow">THE CURRENT PICTURE</span><span className="outline-chip">{coverage} / 4 areas covered</span></div><h3>{status(company)}</h3><p>{concerns?'Your evidence includes warning signs. Verify them, ask direct questions, and prepare options before making a commitment.':coverage?'The available evidence gives you a starting point. It does not establish job security, solvency, or the health of the entity hiring you.':'There is no assessed financial evidence for this company yet. Start with its registered identity, latest accounts, and the questions below.'}</p><div className="coverage-bars" aria-label={`${coverage} of 4 research areas covered`}>{categories.map((c,i)=><span key={c} className={company.evidence.some(e=>e.category===c)?'filled':''}/>)}</div><div className="assessment-bottom"><span><Info size={14}/> Missing data is unknown, never a clean bill of health.</span><button onClick={()=>setTab('method')}>How this works <ArrowUpRight size={14}/></button></div></div>
<div className="section-heading"><h3>Signals that matter</h3><span>{company.evidence.length} evidence items</span></div><div className="signal-grid">{categories.map((c,i)=>{const entries=company.evidence.filter(e=>e.category===c),bad=entries.some(e=>e.signal==='concern');const Icon=[Activity,BriefcaseBusiness,Building2,ShieldCheck][i];return <div className="signal-card" key={c}><div className="signal-top"><Icon size={19}/><span className={'pill '+(bad?'red':entries.length?'green':'gray')}>{bad?'Investigate':entries.length?'Evidence added':'Unknown'}</span></div><h4>{c}</h4><p>{entries.length?entries[0].note:['Cash, debt and the ability to keep operating.','Revenue direction and dependence on customers.','Hiring, turnover and payment patterns.','Filings, ownership and formal proceedings.'][i]}</p></div>})}</div>
<div className="section-heading evidence-title"><h3>The evidence trail</h3><button className="text-button" onClick={()=>setDialog(true)}><Plus size={16}/> Add evidence</button></div>{!company.evidence.length?<div className="empty-evidence"><FileText size={24}/><div><strong>No evidence added yet</strong><p>Add a dated source or a firsthand observation to start your check.</p></div></div>:company.evidence.map(e=><div className="evidence-row" key={e.id}><span className={'evidence-marker '+e.signal}>{e.signal==='positive'?<Check size={16}/>:e.signal==='concern'?'!':'?'}</span><div><div className="evidence-label">{e.category}<span>{e.date||'Date not provided'}</span></div><p>{e.note}</p>{safeURL(e.url)?<a href={safeURL(e.url)} target="_blank" rel="noopener noreferrer">{new URL(e.url).hostname}<ExternalLink size={12}/></a>:<span className="observation">Personal observation · not independently verified</span>}</div><button aria-label="Remove evidence" className="icon-button" onClick={()=>update({...company,evidence:company.evidence.filter(x=>x.id!==e.id)})}><Trash2 size={15}/></button></div>)}
</section><aside><section className="next-card"><span className="eyebrow">MAKE YOUR NEXT MOVE</span><h3>Ask better questions.</h3><p>A company report is only half the conversation.</p><Tabs value={mode} onValueChange={setMode}><TabsList className="mode-tabs"><TabsTrigger value="joining">I'm joining</TabsTrigger><TabsTrigger value="working">I work here</TabsTrigger></TabsList></Tabs><div className="question-list">{(mode==='joining'?questions:['Keep a dated record of changes you observe.','Check whether salary and reimbursements arrive on time.','Ask about team budgets and business priorities.','Update your CV and review your personal cash buffer.']).map((q,i)=>{const id=mode+i;return <label className="question" key={id}><Checkbox checked={company.checks.includes(id)} onCheckedChange={checked=>update({...company,checks:checked?[...company.checks,id]:company.checks.filter(x=>x!==id)})}/><span>{q}</span></label>})}</div><div className="next-note"><Info size={17}/><span>Use this to prepare a conversation, not to predict a closure.</span></div></section>
<section className="research-card"><div className="section-heading"><h3>Start at the source</h3><ArrowUpRight size={18}/></div><p>Confirm the exact legal entity before interpreting company signals.</p><a href="https://www.bizfile.gov.sg/" target="_blank" rel="noopener noreferrer"><span><strong>ACRA Bizfile</strong><small>Registered identity & business records</small></span><ArrowUpRight size={17}/></a><a href="https://www.sgx.com/securities/company-announcements" target="_blank" rel="noopener noreferrer"><span><strong>SGX announcements</strong><small>Disclosures from listed companies</small></span><ArrowUpRight size={17}/></a>{company.id==='grab'&&<a href="https://investors.grab.com/financial-information/quarterly-results/default.aspx" target="_blank" rel="noopener noreferrer"><span><strong>Grab investor relations</strong><small>Check for newer reports</small></span><ArrowUpRight size={17}/></a>}</section><div className="quiet-note"><Eye size={18}/><p>Your notes are personal. Nothing you record here is published about a company.</p></div></aside></div></main></TabsContent>
<TabsContent value="watchlist"><main><div className="page-heading"><div><div className="eyebrow">STAY A STEP AHEAD</div><h1>Your company watchlist.</h1><p>Revisit the evidence as your situation changes.</p></div><button className="primary" onClick={()=>setTab('check')}><Plus size={17}/> New check</button></div><div className="watch-info"><Info size={18}/> Saved on this browser only. Review dates are reminders shown here; no background checks or notifications are sent.</div>{!saved.length?<section className="empty-watch"><Bookmark size={40}/><h2>Keep an eye on what matters.</h2><p>Save a company check to revisit its evidence and plan your next review.</p><button className="primary" onClick={()=>setTab('check')}>Check your first company <ArrowRight size={17}/></button></section>:<div className="watch-grid">{saved.map(c=><section className="watch-card" key={c.id}><div className="watch-card-top"><div className="company-logo">{c.name.slice(0,2).toUpperCase()}</div><button className="icon-button" aria-label={'Remove '+c.name+' from watchlist'} onClick={()=>{setSaved(prev=>prev.filter(x=>x.id!==c.id));toast('Removed from watchlist')}}><Trash2 size={17}/></button></div><h2>{c.name}</h2><p className="watch-status">{status(c)}</p><span className="small">{c.evidence.length} evidence items · {c.reviewed||'Not reviewed'}</span><label className="review-date">Next review<input type="date" value={c.next} onChange={e=>{const updated={...c,next:e.target.value};setSaved(prev=>prev.map(x=>x.id===c.id?updated:x));if(company.id===c.id)setCompany(updated)}}/></label>{c.next&&c.next<=new Date().toISOString().slice(0,10)&&<span className="pill red">Review due</span>}<button className="open-report" onClick={()=>{setCompany(c);setTab('check')}}>Open company check <ArrowRight size={17}/></button></section>)}</div>}</main></TabsContent>
<TabsContent value="method"><main className="method"><div className="eyebrow">EVIDENCE OVER GUESSWORK</div><h1>No magic health score.<br/>A clearer picture.</h1><p className="method-intro">Should I Join helps you organise company evidence before joining an employer, committing to a membership, or deciding how to prepare while you work there.</p><div className="method-grid">{[['01','Know who you are checking','A brand, parent company and local employing entity can be different businesses. Match the registered name and UEN to your contract. Group-level profitability does not establish the position of a subsidiary.'],['02','Keep facts and observations separate','Every evidence item has an area, date and signal selected by you. A linked source remains a source to inspect, not a fact automatically verified by this app. Personal observations are labelled separately.'],['03','Treat unknowns honestly','Coverage counts how many of the four areas have at least one evidence item. It does not measure quality or safety. Any concern produces “Concerns to investigate”; otherwise evidence remains incomplete.'],['04','Revisit, don’t set and forget','Save a check and set a review date. This version has one curated Grab snapshot and manual research for other companies. It does not search live registries, predict insolvency, or send automatic alerts.']].map(([n,t,b])=><section key={n}><span>{n}</span><h2>{t}</h2><p>{b}</p></section>)}</div><div className="method-disclosure"><ShieldCheck size={25}/><div><h3>Designed to support your judgment.</h3><p>Company health can change quickly. This is a research aid, not an employment, legal or financial recommendation. A profitable company can still cut jobs; missing financial statements do not mean a company is in trouble.</p><p>Your watchlist and notes are stored in this browser. Clearing browser data removes them; they do not sync across devices.</p></div></div></main></TabsContent></Tabs>
<footer><span className="footer-brand">should i join?</span><span>Know the company. Own your decision.</span><button onClick={()=>setTab('method')}>Methodology & data coverage <ChevronRight size={14}/></button></footer>{!storageOK&&<div role="alert" className="storage-warning">Browser storage is unavailable. Your changes will last only for this session.</div>}
<Dialog open={dialog} onOpenChange={setDialog}><DialogContent className="evidence-dialog"><DialogHeader><DialogTitle>Add evidence</DialogTitle><DialogDescription>Record what you found about {company.name}. Keep dates and sources specific.</DialogDescription></DialogHeader><form onSubmit={addEvidence}><label>Research area<Select value={category} onValueChange={setCategory}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{categories.map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select></label><label>What does it suggest?<Select value={signal} onValueChange={setSignal}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="unknown">Needs more context</SelectItem><SelectItem value="positive">Positive signal</SelectItem><SelectItem value="concern">Concern to investigate</SelectItem></SelectContent></Select></label><label>Evidence or observation<textarea required maxLength={1500} value={note} onChange={e=>setNote(e.target.value)} placeholder="What happened, and what does the source actually say?"/></label><label>Source URL <span>(optional)</span><input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…"/></label><label>Source / observation date<input type="date" max={new Date().toISOString().slice(0,10)} value={date} onChange={e=>setDate(e.target.value)}/></label><button className="primary" type="submit"><Plus size={17}/> Add to company check</button></form></DialogContent></Dialog></>;
}
