'use client';
import {useEffect,useState} from 'react';
import {Orbit,Activity,ArrowRight,ArrowUpRight,Bookmark,Check,ChevronRight,Clock3,FileText,Info,LayoutGrid,Plus,Search,ShieldCheck,SlidersHorizontal,Trash2,Wallet,TrendingUp,Landmark,Users,Minus,CheckCircle2,CircleHelp,AlertTriangle,ExternalLink} from 'lucide-react';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Toaster,toast} from 'sonner';
import {MetricEditor} from '@/components/company/metric-editor';
import {EvidenceEditor} from '@/components/company/evidence-editor';
import {VisualEvaluation} from '@/components/company/visual-evaluation';
import {specs,summary,evaluate,normalize,safeURL,today,type Company,type MetricId,type Tone} from '@/lib/company/model';
import {sample,questions} from '@/lib/company/data';
const STORE='shouldijoin.workspace.v2',LEGACY='shouldijoin.workspace.v1';
const toneIcons={positive:CheckCircle2,watch:Info,concern:AlertTriangle,unknown:CircleHelp};
function Status({tone,children}:{tone:Tone;children:React.ReactNode}){const Icon=toneIcons[tone];return <span className={'status '+tone}><Icon size={14}/>{children}</span>}
function DateLabel({value}:{value:string}){return <>{value?new Date(value+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}):'No date'}</>}
export default function Home(){
 const [view,setView]=useState('report'),[section,setSection]=useState('metrics'),[query,setQuery]=useState(''),[company,setCompany]=useState<Company>(sample),[saved,setSaved]=useState<Company[]>([]),[ready,setReady]=useState(false),[storageOK,setStorageOK]=useState(true),[metric,setMetric]=useState<MetricId|null>(null),[evidenceOpen,setEvidenceOpen]=useState(false),[mode,setMode]=useState<'joining'|'working'>('joining'),[identity,setIdentity]=useState(false),[identityDraft,setIdentityDraft]=useState('');
 useEffect(()=>{try{const raw=localStorage.getItem(STORE)??localStorage.getItem(LEGACY);if(raw){const data=JSON.parse(raw);if(Array.isArray(data))setSaved(data.map(normalize).filter((c):c is Company=>c!==null));else setStorageOK(false);}}catch{setStorageOK(false)}setReady(true)},[]);
 useEffect(()=>{if(ready&&storageOK){try{localStorage.setItem(STORE,JSON.stringify(saved))}catch{setStorageOK(false)}}},[ready,saved,storageOK]);
 function openCompany(name:string){const clean=name.trim().slice(0,120);if(!clean)return;const stored=saved.find(c=>c.name.toLowerCase()===clean.toLowerCase());setCompany(stored??(/^grab( holdings( limited)?)?$/i.test(clean)?structuredClone(sample):{id:crypto.randomUUID(),name:clean,entity:'Legal entity not confirmed',evidence:[],reviewed:'',next:'',checks:[],metrics:{}}));setView('report');setSection('metrics');setQuery('');}
 function update(next:Company){setCompany(next);setSaved(prev=>prev.map(c=>c.id===next.id?next:c));}
 function save(){setSaved(prev=>[company,...prev.filter(c=>c.id!==company.id)]);toast.success(storageOK?'Company saved on this device':'Company saved for this session only');}
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'start_company_check',description:'Open a company evaluation. Does not fetch live data or save a report.',inputSchema:{type:'object',properties:{companyName:{type:'string',minLength:1,maxLength:120}},required:['companyName'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input:unknown){const name=(input as {companyName?:unknown})?.companyName;if(typeof name!=='string'||!name.trim()||name.length>120)throw Error('Enter a company name of 1–120 characters.');openCompany(name);return {opened:name.trim(),coverage:'Curated Grab snapshot or manual figures'};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort()},[saved]);
 const report=summary(company),isSaved=saved.some(c=>c.id===company.id),selected=specs.find(s=>s.id===metric);
 const priorities=specs.map((s,i)=>({spec:s,result:report.results[i]})).filter(x=>x.result.tone!=='positive').sort((a,b)=>['concern','watch','unknown'].indexOf(a.result.tone)-['concern','watch','unknown'].indexOf(b.result.tone));
 const sourceCount=new Set([...Object.values(company.metrics).map(m=>m?.url).filter(Boolean),...company.evidence.map(e=>e.url).filter(Boolean)]).size;
 return <><Toaster position="bottom-right" theme="dark"/><Tabs value={view} onValueChange={setView} className="app-shell"><header className="site-header"><a href="/" className="brand" aria-label="Should I Join home"><span className="brand-symbol"><Orbit size={25}/></span><span>should i join<span className="brand-question">?</span></span></a><TabsList variant="line" className="main-tabs"><TabsTrigger value="report">Explore</TabsTrigger><TabsTrigger value="watchlist">Watchlist <span className="nav-count">{saved.length}</span></TabsTrigger><TabsTrigger value="method">Methodology</TabsTrigger></TabsList><span className="header-region">Singapore <span>SG</span></span></header>
 <TabsContent value="report"><main className="report-page"><div className="company-command"><div className="report-breadcrumb"><span>COMPANY INTELLIGENCE</span><span>/</span><strong>{company.id==='grab'?'PUBLIC MARKETS':'YOUR RESEARCH'}</strong></div><form className="company-search" onSubmit={e=>{e.preventDefault();openCompany(query)}}><Search size={17}/><input aria-label="Company name or UEN" placeholder="Company name or UEN" required maxLength={120} value={query} onChange={e=>setQuery(e.target.value)}/><button type="submit" aria-label="Open company check"><ArrowRight size={17}/></button></form></div>
 <section className="company-heading"><div className="company-name"><div className="name-line"><h1>{company.name}<span className="company-title-dot">.</span></h1><span className="entity-tag">{company.id==='grab'?'NASDAQ: GRAB':'MANUAL CHECK'}</span></div><button className="entity-link" onClick={()=>{setIdentityDraft(company.entity);setIdentity(true)}}>{company.entity}<SlidersHorizontal size={14}/></button></div><div className="company-actions"><span className="snapshot-stamp"><Clock3 size={14}/>{company.id==='grab'?'Q2 2026 · snapshot':company.reviewed?'Updated '+company.reviewed:'Awaiting figures'}</span><button onClick={save} className={'button save-button '+(isSaved?'is-saved':'')}><Bookmark size={16} fill={isSaved?'currentColor':'none'}/>{isSaved?'Watching':'Watch company'}</button></div></section>
 <div className="report-layout"><div className="evaluation-main"><Tabs value={section} onValueChange={setSection}><div className="section-nav"><TabsList variant="line" className="section-tabs"><TabsTrigger value="metrics"><span className="tab-index">01</span> Overview</TabsTrigger><TabsTrigger value="evidence"><span className="tab-index">02</span> Evidence <span>{company.evidence.length}</span></TabsTrigger><TabsTrigger value="plan"><span className="tab-index">03</span> Next steps</TabsTrigger></TabsList><button className="text-action" onClick={()=>setMetric(priorities[0]?.spec.id??'cashflow')}><Plus size={16}/>Update figures</button></div>
 <TabsContent value="metrics"><VisualEvaluation key={company.id} company={company} onEdit={setMetric} onEvidence={()=>setSection('evidence')} onPlan={()=>setSection('plan')} onMethod={()=>setView('method')}/></TabsContent>
 <TabsContent value="evidence"><section className="evidence-section"><div className="subheading"><div><span className="eyebrow">THE RESEARCH BEHIND THE READOUT</span><h3>Sources & observations</h3></div><button className="button secondary" onClick={()=>setEvidenceOpen(true)}><Plus size={16}/>Add observation</button></div><p className="section-description">Figures and personal observations stay separate. A source link does not mean independent verification.</p><h4 className="list-heading">Metric sources</h4>{specs.filter(s=>company.metrics[s.id]).map(spec=>{const input=company.metrics[spec.id]!;return <article className="source-row" key={spec.id}><FileText size={19}/><div><div className="source-title"><h4>{spec.title}</h4><span><DateLabel value={input.date}/></span></div><p>{input.note||'No additional source details provided.'}</p><div className="source-links"><span>{input.origin==='disclosure'?'Company disclosure · unaudited':'User-entered figures'} · {input.period}</span>{safeURL(input.url)&&<a href={safeURL(input.url)} target="_blank" rel="noopener noreferrer">Open source <ExternalLink size={13}/></a>}</div></div></article>})}{!Object.keys(company.metrics).length&&<div className="empty-inline">Add a metric to attach its figures and source.</div>}<h4 className="list-heading">Observations</h4>{company.evidence.map(e=><article className="source-row observation-row" key={e.id}><Status tone={e.signal==='concern'?'concern':e.signal==='positive'?'positive':'unknown'}>{e.signal==='concern'?'Concern':e.signal==='positive'?'Positive':'Context'}</Status><div><div className="source-title"><h4>{e.category}</h4><span><DateLabel value={e.date}/></span></div><p>{e.note}</p><div className="source-links">{safeURL(e.url)?<a href={safeURL(e.url)} target="_blank" rel="noopener noreferrer">Open source <ExternalLink size={13}/></a>:<span>Personal observation · unverified</span>}</div></div><button className="icon-button" aria-label="Remove observation" onClick={()=>update({...company,evidence:company.evidence.filter(x=>x.id!==e.id)})}><Trash2 size={15}/></button></article>)}{!company.evidence.length&&<div className="empty-inline">No observations yet. Record changes, interview answers or firsthand evidence.</div>}</section></TabsContent>
 <TabsContent value="plan"><section className="plan-section"><div className="subheading"><div><span className="eyebrow">TURN RESEARCH INTO A CONVERSATION</span><h3>Your next steps</h3></div></div><Tabs value={mode} onValueChange={v=>setMode(v as 'joining'|'working')}><TabsList className="mode-tabs"><TabsTrigger value="joining">I'm considering joining</TabsTrigger><TabsTrigger value="working">I already work here</TabsTrigger></TabsList></Tabs><div className="plan-checks">{questions[mode].map((q,i)=>{const id=mode+i;return <label key={id}><Checkbox checked={company.checks.includes(id)} onCheckedChange={checked=>update({...company,checks:checked?[...company.checks,id]:company.checks.filter(c=>c!==id)})}/><span>{q}</span></label>})}</div><div className="review-plan"><div><h4>Set your next review</h4><p>The date appears in your watchlist. No automatic alerts are sent.</p></div><input type="date" aria-label="Next company review" value={company.next} onChange={e=>update({...company,next:e.target.value})}/></div>{!isSaved&&<button onClick={save} className="button primary"><Bookmark size={16}/>Save this company and your progress</button>}</section></TabsContent>
 </Tabs></div>
</div></main></TabsContent>
 <TabsContent value="watchlist"><main><div className="workspace-toolbar"><div><span className="eyebrow">YOUR RESEARCH, IN ONE PLACE</span><h1>Company watchlist</h1></div><button className="button primary" onClick={()=>setView('report')}><Plus size={16}/>Company check</button></div><p className="watchlist-note">Saved in this browser. Review dates appear here; background monitoring and notifications are not connected.</p>{!saved.length?<section className="empty-watch"><Bookmark size={32}/><h2>No companies saved yet.</h2><p>Save an evaluation to keep its figures, evidence and your next review date.</p><button onClick={()=>setView('report')} className="button primary">Open an evaluation <ArrowRight size={17}/></button></section>:<div className="watch-grid">{saved.map(c=>{const s=summary(c);return <section className="watch-card" key={c.id}><div className="watch-title"><div className="company-mark">{c.name.slice(0,1).toUpperCase()}</div><button className="icon-button" aria-label={'Remove '+c.name} onClick={()=>{setSaved(prev=>prev.filter(x=>x.id!==c.id));toast('Removed from watchlist')}}><Trash2 size={17}/></button></div><h2>{c.name}</h2><p>{s.title}</p><div className="watch-signals"><span>{s.positive} positive</span><span>{s.watch+s.concern} to review</span><span>{s.unknown} unknown</span></div><label className="watch-date">Next review<input type="date" value={c.next} onChange={e=>{const next={...c,next:e.target.value};setSaved(prev=>prev.map(x=>x.id===c.id?next:x));if(company.id===c.id)setCompany(next)}}/></label>{c.next&&c.next<=today()&&<Status tone="watch">Review due</Status>}<button className="watch-open" onClick={()=>{setCompany(c);setView('report');setSection('metrics')}}>Open evaluation <ArrowRight size={17}/></button></section>})}</div>}</main></TabsContent>
 <TabsContent value="method"><main className="method-page"><span className="eyebrow">HOW TO READ THE SIGNALS</span><h1>Useful metrics.<br/>Visible assumptions.</h1><p className="method-intro">Six separate readings help you ask better questions. They do not predict a closure or guarantee a job.</p><section className="method-explainer"><h2>How the visual works</h2><p>3D pillar heights show three screening bands, not financial magnitude. Hollow outlines mean unknown or stale information. Select a pillar to see exact values and a chart in that metric’s own units. The 2D view shows the same bands as a matrix.</p><h2>How the readout works</h2><p>A numeric concern or an observation marked “Concern” takes priority. Otherwise, a watch reading prompts further questions; missing or stale figures keep the assessment incomplete. Only six current positive readings produce “Available signals are positive”.</p><p>Figures more than 180 days old become “Needs updating”. This is a product freshness rule, not a guarantee that newer information is accurate. Cash runway with zero net burn is shown as not applicable, never infinite.</p></section><div className="method-metrics">{specs.map(s=><section key={s.id}><span className="eyebrow">{s.group}</span><h2>{s.title}</h2><p className="method-formula">{s.formula}</p><div className="reference-bands">{s.bands.map(b=><span key={b}>{b}</span>)}</div><p>{s.caveat}</p></section>)}</div><section className="method-explainer"><h2>Coverage and privacy</h2><p>Grab is a manually curated, unaudited Q2 2026 group snapshot. Other companies require your own figures and sources. Live registry lookup, financial feeds and automatic alerts are not connected. No source URL is automatically verified.</p><p>Match the legal entity and UEN on your contract. Group cash or profitability may not be available to the entity employing you. Salary reliability applies to the three payment cycles recorded, not to all employees.</p><p>Your existing watchlist and observations are preserved on this device. Nothing you enter is published to other visitors. Clearing browser data removes your saved research; it does not sync across devices.</p></section></main></TabsContent>
 <div className="coverage-note"><span>Curated report: <button onClick={()=>openCompany('Grab')}>Grab <ArrowUpRight size={13}/></button></span><span>Other companies use your figures. Live search is not connected.</span><span>Private notes · this device</span></div></Tabs><footer><span>should i join?</span><span>Research for your next move.</span><button onClick={()=>setView('method')}>Data & methodology <ArrowUpRight size={14}/></button></footer>
 {!storageOK&&<div className="storage-warning" role="alert">Browser storage is unavailable or unreadable. Existing stored data has been left untouched; new changes last for this session only.</div>}
 {selected&&<MetricEditor key={company.id+selected.id} spec={selected} input={company.metrics[selected.id]} onClose={()=>setMetric(null)} onSave={input=>{const metrics={...company.metrics};if(input)metrics[selected.id]=input;else delete metrics[selected.id];update({...company,metrics,reviewed:today()});toast.success(isSaved?'Metric updated and saved':'Metric updated — save this company to keep your figures');}}/>}
 {evidenceOpen&&<EvidenceEditor name={company.name} onClose={()=>setEvidenceOpen(false)} onSave={e=>{update({...company,evidence:[...company.evidence,e],reviewed:today()});toast.success(isSaved?'Observation saved':'Observation added — save the company to keep it');}}/>}
 <Dialog open={identity} onOpenChange={setIdentity}><DialogContent className="metric-dialog"><DialogHeader><DialogTitle>Company identity & scope</DialogTitle><DialogDescription>Record the registered name, UEN and whether these figures describe the group or the entity on your contract.</DialogDescription></DialogHeader><form className="editor-form" onSubmit={e=>{e.preventDefault();update({...company,entity:identityDraft.trim()});setIdentity(false)}}><label>Registered entity / scope<input required maxLength={250} value={identityDraft} onChange={e=>setIdentityDraft(e.target.value)}/></label><p className="metric-caveat"><Info size={16}/>This is your identity note. It does not verify the entity against ACRA.</p><button className="button primary" type="submit">Update identity note</button></form></DialogContent></Dialog>
 </>;
}
